name: Chore Item
description: Anything clerical or not quite a feature
title: "Chore | [DESCRIPTION]"
labels: ["chore"]
assignees:
  - Harrison-Blair
body:
  - type: textarea
    id: description
    attributes:
      label: What needs to be done?
      description: Describe the chore
    validations:
      required: true
  
  - type: dropdown
    id: chore-type
    attributes:
      label: Chore Type
      options:
        - Refactoring
        - Maintenance
        - Cleanup
        - Configuration
        - Dependencies
        - Other
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  
  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      options:
        - XS (< 1 hour)
        - S (1-4 hours)
        - M (1-2 days)
        - L (3-5 days)
        - XL (1-2 weeks)
  
  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Why does this need to be done?
    validations:
      required: true
  
  - type: checkboxes
    id: done-criteria
    attributes:
      label: Definition of Done
      description: Check all that apply when complete
      options:
        - label: Code changes complete
        - label: Tests added/updated
        - label: Documentation updated
        - label: Reviewed and approved
  
  - type: textarea
    id: related-items
    attributes:
      label: Related Work Items
      placeholder: "#123, #456"